### ISSUE TITLE
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: null.  Check the render method of `Ac`.

### ISSUE THREAD

**Issue by kwanmo2** [notionpresso/nextjs-blog-template#8]
After following the instructions, it worked fine to import the posts(json file) and images from notion, but when I clicked on a newly created post on the main page, I got the error message below(on both Mac and Windows). 

![image](https://github.com/user-attachments/assets/80b3c8a2-6e08-4732-8d42-d30ee0f9b1f1)
![image](https://github.com/user-attachments/assets/7948e9fb-4e7b-4e03-a852-46df98708d61)

Where should I check?

The example post, on the other hand, works fine.
![image](https://github.com/user-attachments/assets/fa13ae5c-7e44-4f8c-a8bc-360bdc37f02b)

my env is below.
![image](https://github.com/user-attachments/assets/da796570-6d1e-48f1-82f7-3b6da5b5903a)

**Comment by anonymousRecords** [comment]
@kwanmo2 
Currently, this is our list of supported Notion blocks (https://github.com/notionpresso/react/issues/55). 
It seems that **when using Notion blocks that are not yet supported, you might receive the error message you shared.** Could you please check if this applies to your situation?

**Comment by kwanmo2** [comment]
Thanks a lot. after removing links, it works.
